"""Add transmission and seats to Car model

Revision ID: 21ba5ccd327a
Revises: 
Create Date: 2025-06-07 19:58:16.363209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ba5ccd327a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('seats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('seats')
        batch_op.drop_column('transmission')

    # ### end Alembic commands ###
