""" Fix reservation history with constraint name

Revision ID: 7bd46ff7b2b5
Revises: 9623261b0d7c
Create Date: 2025-06-05 18:46:20.442967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd46ff7b2b5'
down_revision = '9623261b0d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reservation')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('action_date')
        batch_op.drop_column('car_brand')
        batch_op.drop_column('car_model')

    with op.batch_alter_table('reservation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('action_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_reservationhistory_car_id', 'car', ['car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservationhistory_car_id', type_='foreignkey')
        batch_op.drop_column('action_date')
        batch_op.drop_column('action')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('car_id')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_model', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('car_brand', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('action_date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_id_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('customer_license_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('car_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
