"""Add cloudinary_url with default

Revision ID: d5840c04e2b0
Revises: c32408750723
Create Date: 2025-06-09 03:21:02.009681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5840c04e2b0'
down_revision = 'c32408750723'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('car_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=300), nullable=False, server_default=''))
        batch_op.drop_column('image_filename')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('cloudinary_url')

    # ### end Alembic commands ###
